//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books_To_Readers
    {
        public int id { get; set; }
        public Nullable<int> Book_id { get; set; }
        public Nullable<int> Reader_id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
