//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Books_To_Authors = new HashSet<Books_To_Authors>();
            this.Books_To_Readers = new HashSet<Books_To_Readers>();
        }
    
        public int id { get; set; }
        public string BookName { get; set; }
        public string Content { get; set; }
        public string Photo { get; set; }
        public string PDFfile { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<int> GivenBook { get; set; }
        public Nullable<byte> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books_To_Authors> Books_To_Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books_To_Readers> Books_To_Readers { get; set; }
    }
}
